"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, MessageSquare, Image, Sparkles, Volume2, BookOpen, Check, Wand2 } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { toast } from "sonner";
import { languageLabel, isRTLText, nativeScriptInstruction, usesNikud } from "@/lib/language";

export default function ClickableWord({
  word, // target-language native word (Hebrew by default)
  transliteration, // phonetic/transliteration
  translation, // English meaning
  className = "",
  variant = "hebrew", // "hebrew" | "transliteration" | "both"
  onBeforeOpen, // callback to pause video
  editable = false, // if true, show edit on click
  onEdit, // callback when editing
  language // target language (e.g. word.language); defaults to Hebrew to preserve current behavior
}) {
  // Target language for AI prompts. Falls back to Hebrew (unchanged behavior).
  const lang = language || 'hebrew';
  const [open, setOpen] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(word);
  const [activeTab, setActiveTab] = useState("sentences"); // "sentences" | "mnemonic"
  const [loading, setLoading] = useState(false);
  const [sentences, setSentences] = useState(null);
  const [mnemonicSuggestions, setMnemonicSuggestions] = useState(null);
  const [customDescription, setCustomDescription] = useState("");
  const [generatedImage, setGeneratedImage] = useState(null);
  const [generatingCustom, setGeneratingCustom] = useState(false);

  const handleClick = (e) => {
    if (editable && e.ctrlKey) {
      e.stopPropagation();
      setIsEditing(true);
      return;
    }
    if (onBeforeOpen) {
      onBeforeOpen();
    }
    setOpen(true);
  };

  const handleSaveEdit = () => {
    if (onEdit && editValue !== word) {
      onEdit(editValue);
    }
    setIsEditing(false);
  };

  const generateSentences = async () => {
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Create 5 example sentences using the ${languageLabel(lang)} word "${word}" (${transliteration}) which means "${translation}".
        Return each sentence's ${nativeScriptInstruction(lang)} in the "hebrew" field, plus an English translation with phonetic pronunciation.
        Make sentences progressively harder from beginner to advanced.`,
        response_json_schema: {
          type: "object",
          properties: {
            sentences: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  hebrew: { type: "string" },
                  phonetic: { type: "string" },
                  english: { type: "string" },
                  difficulty: { type: "string" }
                }
              }
            }
          }
        }
      });
      setSentences(result.sentences);
    } catch (e) {
      toast.error("Failed to generate sentences");
    }
    setLoading(false);
  };

  const generateMnemonicSuggestions = async () => {
    if (mnemonicSuggestions) return;
    setLoading(true);
    try {
      const result = await base44.integrations.Core.InvokeLLM({
        prompt: `Create 3 different mnemonic image ideas to help remember the ${languageLabel(lang)} word "${word}" (${transliteration}) which means "${translation}".
        Each mnemonic should use the SOUND of the ${languageLabel(lang)} word to create a memorable visual scene.
        Be creative and make them funny, absurd, or memorable.
        Describe each image in detail so it can be generated by AI.`,
        response_json_schema: {
          type: "object",
          properties: {
            suggestions: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  title: { type: "string" },
                  description: { type: "string" },
                  imagePrompt: { type: "string" }
                }
              }
            }
          }
        }
      });
      setMnemonicSuggestions(result.suggestions);
    } catch (e) {
      toast.error("Failed to generate suggestions");
    }
    setLoading(false);
  };

  const generateMnemonicImage = async (prompt) => {
    setGeneratingCustom(true);
    try {
      const result = await base44.integrations.Core.GenerateImage({
        prompt: `A colorful, memorable mnemonic illustration: ${prompt}.
        For learning ${languageLabel(lang)} word "${transliteration}" meaning "${translation}".
        Cartoon style, vibrant colors, educational, fun and memorable.`
      });
      setGeneratedImage(result.url);
      toast.success("Mnemonic image generated!");
    } catch (e) {
      toast.error("Failed to generate image");
    }
    setGeneratingCustom(false);
  };

  const saveSentence = async (sentence) => {
    await base44.entities.Word.create({
      word: sentence.hebrew,
      translation: sentence.english,
      phonetic: sentence.phonetic,
      category: "sentences",
      difficulty: "beginner",
    });
    toast.success("Sentence saved to Word Bank!");
  };

  const saveWord = async () => {
    try {
      // If translation is missing, fetch it first
      let finalTranslation = translation;
      let finalTransliteration = transliteration;
      
      if (!finalTranslation || !finalTransliteration) {
        setLoading(true);
        const result = await base44.integrations.Core.InvokeLLM({
          prompt: usesNikud(lang)
            ? `Translate the word "${word}" from ${languageLabel(lang)} to English. Provide the transliteration and meaning.`
            : `Translate the word "${word}" from ${languageLabel(lang)} to English. Provide the meaning, and a transliteration (for a Latin-script language this can simply be the word itself).`,
          response_json_schema: {
            type: "object",
            properties: {
              transliteration: { type: "string" },
              translation: { type: "string" }
            }
          }
        });
        finalTransliteration = finalTransliteration || result.transliteration;
        finalTranslation = finalTranslation || result.translation;
        setLoading(false);
      }

      await base44.entities.Word.create({
        word: word,
        translation: finalTranslation,
        phonetic: finalTransliteration,
        category: "wordbank",
        times_practiced: 1,
        mastered: false,
      });
      toast.success("Word added to backpack! 🎒");
      setOpen(false);
    } catch (e) {
      toast.error("Failed to save word");
      setLoading(false);
    }
  };

  const displayText = variant === "hebrew" ? word : 
                      variant === "transliteration" ? transliteration : 
                      `${word} (${transliteration})`;

  return (
    <>
      {isEditing ? (
        <input
          type="text"
          value={editValue}
          onChange={(e) => setEditValue(e.target.value)}
          onBlur={handleSaveEdit}
          onKeyDown={(e) => {
            if (e.key === "Enter") handleSaveEdit();
            if (e.key === "Escape") { setEditValue(word); setIsEditing(false); }
          }}
          autoFocus
          className="inline-block bg-cyan-500/20 border border-cyan-400 rounded px-1 outline-none text-white"
          style={{ width: `${Math.max(editValue.length * 10, 40)}px` }}
          onClick={(e) => e.stopPropagation()}
        />
      ) : (
        <span
          onClick={handleClick}
          className={`cursor-pointer hover:bg-cyan-500/30 hover:text-cyan-300 px-1 rounded transition-all underline decoration-dotted underline-offset-4 ${className}`}
          title={editable ? "Ctrl+Click to edit" : ""}
        >
          {displayText}
        </span>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="bg-slate-900 border-white/20 text-white max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Sparkles className="w-6 h-6 text-cyan-400" />
                <div>
                  <span className="text-2xl" dir={isRTLText(word) ? "rtl" : "ltr"}>{word}</span>
                  <span className="text-white/60 ml-3">/{transliteration}/</span>
                  <span className="text-cyan-400 ml-3">{translation}</span>
                </div>
              </div>
              <Button
                onClick={saveWord}
                disabled={loading}
                className="bg-amber-500 hover:bg-amber-600 flex-shrink-0"
                size="sm"
              >
                {loading ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Saving...</>
                ) : (
                  <><BookOpen className="w-4 h-4 mr-2" /> Add to Backpack</>
                )}
              </Button>
            </DialogTitle>
          </DialogHeader>

          {/* Tabs */}
          <div className="flex gap-2 mb-4">
            <Button
              variant={activeTab === "sentences" ? "default" : "outline"}
              onClick={() => setActiveTab("sentences")}
              className={activeTab === "sentences" ? "bg-cyan-500" : "border-white/20 text-white"}
            >
              <MessageSquare className="w-4 h-4 mr-2" />
              Sentences
            </Button>
            <Button
              variant={activeTab === "mnemonic" ? "default" : "outline"}
              onClick={() => { setActiveTab("mnemonic"); generateMnemonicSuggestions(); }}
              className={activeTab === "mnemonic" ? "bg-purple-500" : "border-white/20 text-white"}
            >
              <Image className="w-4 h-4 mr-2" />
              Mnemonic Picture
            </Button>
          </div>

          {/* Sentences Tab */}
          {activeTab === "sentences" && (
            <div className="space-y-3">
              {!sentences && !loading && (
                <div className="text-center py-8">
                  <Button onClick={generateSentences} className="bg-cyan-500 hover:bg-cyan-600">
                    <Sparkles className="w-4 h-4 mr-2" />
                    Generate Example Sentences
                  </Button>
                </div>
              )}
              {loading ? (
                <div className="flex flex-col items-center py-8">
                  <Loader2 className="w-8 h-8 text-cyan-400 animate-spin mb-3" />
                  <p className="text-white/60">Generating sentences...</p>
                </div>
              ) : sentences ? (
                sentences.map((s, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="bg-white/5 border border-white/10 rounded-xl p-4"
                  >
                    <div className="flex justify-between items-start mb-2">
                      <span className="text-xs bg-white/10 px-2 py-1 rounded-full text-white/60">
                        {s.difficulty || `Example ${i + 1}`}
                      </span>
                      <Button
                        size="sm"
                        onClick={() => saveSentence(s)}
                        className="bg-green-500/20 text-green-400 hover:bg-green-500/30 h-7"
                      >
                        <BookOpen className="w-3 h-3 mr-1" /> Save
                      </Button>
                    </div>
                    <p className="text-lg text-cyan-400 mb-1" dir={isRTLText(s.hebrew) ? "rtl" : "ltr"}>{s.hebrew}</p>
                    <p className="text-white/60 text-sm mb-1">{s.phonetic}</p>
                    <p className="text-white/80">{s.english}</p>
                  </motion.div>
                ))
              ) : null}
            </div>
          )}

          {/* Mnemonic Tab */}
          {activeTab === "mnemonic" && (
            <div className="space-y-4">
              {/* Custom Description - ON TOP */}
              <div className="bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/30 rounded-xl p-4">
                <h4 className="text-sm font-semibold text-white/80 mb-2">✨ Describe your own mnemonic:</h4>
                <Textarea
                  value={customDescription}
                  onChange={(e) => setCustomDescription(e.target.value)}
                  placeholder="Describe the image you want... e.g., 'A cat sitting on a chair eating shalom-shaped cookies'"
                  className="bg-white/5 border-white/20 text-white placeholder:text-white/40 mb-3"
                  rows={3}
                />
                <Button
                  onClick={() => generateMnemonicImage(customDescription)}
                  disabled={!customDescription.trim() || generatingCustom}
                  className="w-full bg-gradient-to-r from-purple-500 to-pink-500"
                >
                  {generatingCustom ? (
                    <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...</>
                  ) : (
                    <><Wand2 className="w-4 h-4 mr-2" /> Generate My Mnemonic</>
                  )}
                </Button>
              </div>

              {/* Generated Image */}
              {generatedImage && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                >
                  <h4 className="text-sm font-semibold text-green-400 mb-2">✓ Your Mnemonic Image:</h4>
                  <img
                    src={generatedImage}
                    alt="Mnemonic"
                    className="w-full rounded-xl shadow-lg border border-white/20"
                  />
                </motion.div>
              )}

              {/* 3 AI Suggestions */}
              {loading && !mnemonicSuggestions ? (
                <div className="flex flex-col items-center py-8">
                  <Loader2 className="w-8 h-8 text-purple-400 animate-spin mb-3" />
                  <p className="text-white/60">Generating mnemonic ideas...</p>
                </div>
              ) : mnemonicSuggestions && (
                <div className="space-y-3">
                  <h4 className="text-sm font-semibold text-white/60">Or choose from AI suggestions:</h4>
                  {mnemonicSuggestions.map((suggestion, i) => (
                    <motion.div
                      key={i}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: i * 0.1 }}
                      className="bg-white/5 border border-white/10 rounded-xl p-4"
                    >
                      <div className="flex justify-between items-start">
                        <div className="flex-1">
                          <h5 className="font-bold text-purple-300 mb-1">{suggestion.title}</h5>
                          <p className="text-white/70 text-sm">{suggestion.description}</p>
                        </div>
                        <Button
                          size="sm"
                          onClick={() => generateMnemonicImage(suggestion.imagePrompt)}
                          disabled={generatingCustom}
                          className="bg-purple-500 hover:bg-purple-600 ml-3"
                        >
                          {generatingCustom ? <Loader2 className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                        </Button>
                      </div>
                    </motion.div>
                  ))}
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}